import * as fs from 'node:fs';
import * as path from 'node:path';
import { LLMProvider } from '../providers/base';
import { treePath } from '../config';

const IGNORED = new Set(['node_modules', '.git', 'dist', 'build', '.aiv', '.next', 'coverage', '.cache', 'out', '__pycache__']);
const SOURCE_EXT = /\.(ts|js|tsx|jsx|py|go|java|rb|php|cs|rs|kt|swift)$/;
const CONFIG_EXT = /\.(json|yaml|yml|toml|env\.example|env\.sample)$/;

const EDITORIAL_HEADER = `<!-- =========================================================
  aiv context.md — auto-generated by \`aiv context generate\`

  READ THIS FILE and edit it before your first review.
  The more accurate this file is, the better the AI findings will be.

  Key sections to review:
    - Business Rules: these directly drive agent findings — add real invariants
    - Sensitive Zones: add any path that handles money, auth, or PII
    - Architecture: correct any wrong assumptions about your layer structure
========================================================= -->

`;

export async function generateContextAndRules(
  cwd: string,
  provider: LLMProvider,
): Promise<{ context: string; rules: string }> {
  const name = path.basename(cwd);

  const treeFile = treePath(cwd);
  const treeData = fs.existsSync(treeFile)
    ? fs.readFileSync(treeFile, 'utf8').slice(0, 10000)
    : '(tree not available — run aiv context refresh first)';

  const pkgInfo   = readPackageJson(cwd);
  const readme    = readReadme(cwd);
  const configs   = readConfigFiles(cwd);
  const sources   = readSourceFiles(cwd);

  const userMessage = `Project name: ${name}

## package.json
${pkgInfo}

## README (if present)
${readme}

## Config files (tsconfig, env.example, etc.)
${configs}

## Project file tree
${treeData}

## Source files sample
${sources}

Analyze this project thoroughly and generate context.md and rules.yml for AI PR reviewers.
Return ONLY valid JSON: { "context": "<context.md content>", "rules": "<rules.yml content>" }`;

  const systemPrompt = `You are an expert software architect analyzing a codebase to generate AI reviewer context.

Your output must help AI agents understand:
1. How the project is structured and what each layer/module does
2. What business domain it operates in and what invariants must hold
3. Which parts are security-sensitive or require extra care
4. What architectural patterns the project follows (so deviations can be flagged)

Generate two files:

### context.md — include ALL of these sections:

## Business Context
Describe the business domain (e-commerce, fintech, healthcare, SaaS, etc.) and what the system does.
State the most critical business invariants — rules that must NEVER be violated (e.g., "balances must never go negative", "all payments require an audit log").

## Architecture
Describe the overall pattern: monolith/microservices/monorepo, layering (handlers → services → repositories), module structure, main data flows.
Name the layers explicitly so agents can flag violations.

## Modules
List each significant module/directory with a one-line description of its responsibility.

## Technologies
Main frameworks, ORMs, auth libraries, messaging systems, etc.

## Critical Dependencies
Security-sensitive packages (auth, crypto, payments, HTTP clients).

## Sensitive Zones
Exact file paths or directories that handle: authentication, payments/billing, PII, database migrations, permissions.
Format as a list: "- src/auth/ — JWT issuance and session management"

## Business Rules
IMPORTANT: infer real domain rules from the code. Examples:
- "All mutations in src/payments/ must call auditLog()"
- "User balance must only be modified via BalanceService, never directly"
- "Orders cannot transition from COMPLETED to any other state"
Be specific. Vague rules produce vague findings.

## System Summary
Two-sentence description of what the system does and who uses it.

### rules.yml — infer real module names and rules:

sensitive_modules: [list actual folder names that are sensitive]
business_rules:
  <real_module_name>:
    required_calls: [actual function names that must be called]
    required_checks: [actual validation functions/guards]
    forbidden_patterns: [actual antipatterns found or expected]

Use only real names from the file tree. No generic placeholders like "your-module".
Return ONLY the JSON object — no markdown fences, no explanation outside the JSON.`;

  const response = await provider.complete(
    [{ role: 'user', content: userMessage }],
    systemPrompt,
    6000,
  );

  const result = parseResponse(response.content);
  result.context = EDITORIAL_HEADER + result.context;
  return result;
}

function parseResponse(raw: string): { context: string; rules: string } {
  const jsonMatch = /\{[\s\S]*\}/.exec(raw.trim());
  if (!jsonMatch) throw new Error('AI returned no JSON');

  try {
    const parsed = JSON.parse(jsonMatch[0]) as { context?: string; rules?: string };
    if (!parsed.context || !parsed.rules) throw new Error('missing fields');
    return { context: parsed.context, rules: parsed.rules };
  } catch {
    return {
      context: raw,
      rules: 'sensitive_modules: []\nbusiness_rules: {}\n',
    };
  }
}

function readPackageJson(cwd: string): string {
  const file = path.join(cwd, 'package.json');
  if (!fs.existsSync(file)) return '(not found)';
  try {
    const pkg = JSON.parse(fs.readFileSync(file, 'utf8'));
    const deps = Object.keys({ ...pkg.dependencies, ...pkg.devDependencies });
    return `name: ${pkg.name ?? '?'}\nversion: ${pkg.version ?? '?'}\nscripts: ${Object.keys(pkg.scripts ?? {}).join(', ')}\ndependencies (${deps.length}): ${deps.join(', ')}`;
  } catch {
    return '(unreadable)';
  }
}

function readReadme(cwd: string): string {
  for (const name of ['README.md', 'readme.md', 'README.txt', 'README']) {
    const file = path.join(cwd, name);
    if (fs.existsSync(file)) {
      try { return fs.readFileSync(file, 'utf8').slice(0, 3000); } catch {}
    }
  }
  return '(not found)';
}

function readConfigFiles(cwd: string): string {
  const candidates = [
    'tsconfig.json', 'jsconfig.json',
    '.env.example', '.env.sample', '.env.template',
    'docker-compose.yml', 'docker-compose.yaml',
    'angular.json', 'nest-cli.json', 'vite.config.ts', 'vite.config.js',
    'next.config.js', 'next.config.ts',
  ];

  const parts: string[] = [];
  for (const name of candidates) {
    const file = path.join(cwd, name);
    if (!fs.existsSync(file)) continue;
    try {
      const content = fs.readFileSync(file, 'utf8').slice(0, 800);
      parts.push(`--- ${name} ---\n${content}`);
    } catch {}
    if (parts.length >= 4) break;
  }
  return parts.join('\n\n') || '(none found)';
}

function readSourceFiles(cwd: string): string {
  const srcRoots = ['src', 'app', 'lib', 'packages', 'modules', 'server', 'api']
    .map(d => path.join(cwd, d))
    .filter(d => { try { return fs.statSync(d).isDirectory(); } catch { return false; } });

  const files: string[] = [];

  // Prioritize key files: services, controllers, models, auth, guards, interceptors
  const priority = /\.(service|controller|model|entity|repository|guard|middleware|interceptor|router|handler|resolver)\.(ts|js)$/i;

  for (const root of srcRoots) {
    collectSourceFiles(root, files, priority);
  }
  for (const root of srcRoots) {
    collectSourceFiles(root, files, null);
    if (files.length >= 40) break;
  }

  const unique = [...new Set(files)].slice(0, 40);
  return unique.map(f => {
    const rel = path.relative(cwd, f);
    const content = fs.readFileSync(f, 'utf8').slice(0, 600);
    return `--- ${rel} ---\n${content}`;
  }).join('\n\n').slice(0, 20000);
}

function collectSourceFiles(dir: string, out: string[], filter: RegExp | null, depth = 0): void {
  if (depth > 5 || out.length >= 40) return;
  let entries: string[];
  try { entries = fs.readdirSync(dir); } catch { return; }

  for (const entry of entries) {
    if (IGNORED.has(entry)) continue;
    processEntry(path.join(dir, entry), entry, out, filter, depth);
    if (out.length >= 40) break;
  }
}

function processEntry(full: string, name: string, out: string[], filter: RegExp | null, depth: number): void {
  try {
    const stat = fs.statSync(full);
    if (stat.isFile()) {
      const matches = filter ? filter.test(name) : SOURCE_EXT.test(name);
      if (matches && !out.includes(full)) out.push(full);
    } else if (stat.isDirectory()) {
      collectSourceFiles(full, out, filter, depth + 1);
    }
  } catch {}
}
