import * as fs from 'node:fs';
import * as path from 'node:path';
import { LLMProvider } from '../providers/base';
import { treePath } from '../config';
import { buildGraphifyContext } from './graphify';

const IGNORED = new Set(['node_modules', '.git', 'dist', 'build', '.aiv', '.next', 'coverage', '.cache', 'out', '__pycache__', '.venv', 'venv']);
const SOURCE_EXT = /\.(ts|js|tsx|jsx|py|go|java|rb|php|cs|rs|kt|swift)$/;

const ENTRY_PATTERN  = /^(main|index|app|app\.module|server|bootstrap)\.(ts|js)$/i;
const LOGIC_SUFFIXES = new Set([
  'service', 'controller', 'model', 'entity', 'repository',
  'guard', 'middleware', 'interceptor', 'router', 'handler', 'resolver',
  'use-case', 'usecase', 'component', 'module', 'pipe', 'directive',
  'store', 'reducer', 'effect', 'action', 'selector', 'hook',
  'composable', 'provider', 'schema', 'dto', 'vo', 'command', 'query', 'event',
]);
const TEST_PATTERN   = /\.(spec|test)\.(ts|js|tsx|jsx)$/i;

function isLogicFile(name: string): boolean {
  const parts = name.toLowerCase().split('.');
  return parts.length >= 3 && LOGIC_SUFFIXES.has(parts.at(-2) ?? '');
}

const EDITORIAL_HEADER = `<!-- =========================================================
  aiv context.md — auto-generated by \`aiv context generate\`

  READ THIS FILE and edit it before your first review.
  The more accurate this file is, the better the AI findings will be.

  Key sections to review:
    - Business Rules: these directly drive agent findings — add real invariants
    - Sensitive Zones: add any path that handles money, auth, or PII
    - Architecture: correct any wrong assumptions about your layer structure
========================================================= -->

`;

export async function generateContextAndRules(
  cwd: string,
  provider: LLMProvider,
): Promise<{ context: string; rules: string }> {
  const name = path.basename(cwd);

  const treeFile = treePath(cwd);
  const treeData = fs.existsSync(treeFile)
    ? fs.readFileSync(treeFile, 'utf8').slice(0, 8000)
    : '(tree not available — run aiv context refresh first)';

  const pkgInfo     = readPackageJson(cwd);
  const readme      = readReadme(cwd);
  const configs     = readConfigFiles(cwd);
  const sources     = readSourceFiles(cwd);
  const graphifyCtx = buildGraphifyContext(cwd);

  const graphifySection = graphifyCtx
    ? `\n## Knowledge Graph (graphify — nodes, edges, call flows)\n${graphifyCtx}`
    : '';

  const userMessage = `Project name: ${name}

## package.json
${pkgInfo}

## README (if present)
${readme}

## Config files (tsconfig, env.example, etc.)
${configs}

## Project file tree
${treeData}

## Source files sample
${sources}
${graphifySection}

Analyze this project thoroughly and generate context.md and rules.yml for AI PR reviewers.
${graphifyCtx ? 'The knowledge graph above shows real dependency relationships — use it to infer call flows, module boundaries, and data paths.' : ''}
Return ONLY valid JSON: { "context": "<context.md content>", "rules": "<rules.yml content>" }`;

  const systemPrompt = `You are an expert software architect analyzing a codebase to generate AI reviewer context.

Your output must help AI agents understand:
1. How the project is structured and what each layer/module does
2. What business domain it operates in and what invariants must hold
3. Which parts are security-sensitive or require extra care
4. What architectural patterns the project follows (so deviations can be flagged)

Pay special attention to TEST FILES — they are the best documentation of business intent.
A test like "should not allow negative balance" tells you a business invariant.
A test like "should require admin role" tells you an access control rule.
Extract these as explicit business rules.

Generate two files:

### context.md — include ALL of these sections:

## Business Context
Describe the business domain and what the system does.
State the most critical business invariants — rules that must NEVER be violated.

## Architecture
Overall pattern: monolith/microservices/monorepo, layering (handlers → services → repositories), module structure.
Name the layers explicitly so agents can flag violations.

## Modules
List each significant module/directory with a one-line description.

## Technologies
Main frameworks, ORMs, auth libraries, messaging systems, etc.

## Critical Dependencies
Security-sensitive packages (auth, crypto, payments, HTTP clients).

## Sensitive Zones
Exact file paths or directories that handle: authentication, payments/billing, PII, database migrations, permissions.
Format: "- src/auth/ — JWT issuance and session management"

## Business Rules
Infer REAL domain rules from the code and tests. Be specific:
- "All mutations in src/payments/ must call auditLog()"
- "User balance must only be modified via BalanceService, never directly"
- "Orders cannot transition from COMPLETED to any other state"

## System Summary
Two-sentence description of what the system does and who uses it.

### rules.yml — infer real module names and rules from the code:

sensitive_modules: [list actual folder names that are sensitive]
business_rules:
  <real_module_name>:
    required_calls: [actual function names that must be called]
    required_checks: [actual validation functions/guards]
    forbidden_patterns: [actual antipatterns found or expected]

Use only real names from the file tree. No generic placeholders.
Return ONLY the JSON object — no markdown fences, no explanation outside the JSON.`;

  const response = await provider.complete(
    [{ role: 'user', content: userMessage }],
    systemPrompt,
    8000,
  );

  const result = parseResponse(response.content);
  result.context = EDITORIAL_HEADER + result.context;
  return result;
}

function parseResponse(raw: string): { context: string; rules: string } {
  const jsonMatch = /\{[\s\S]*\}/.exec(raw.trim());
  if (!jsonMatch) throw new Error('AI returned no JSON');

  try {
    const parsed = JSON.parse(jsonMatch[0]) as { context?: string; rules?: string };
    if (!parsed.context || !parsed.rules) throw new Error('missing fields');
    return { context: parsed.context, rules: parsed.rules };
  } catch {
    return {
      context: raw,
      rules: 'sensitive_modules: []\nbusiness_rules: {}\n',
    };
  }
}

function readPackageJson(cwd: string): string {
  const file = path.join(cwd, 'package.json');
  if (!fs.existsSync(file)) return '(not found)';
  try {
    const pkg = JSON.parse(fs.readFileSync(file, 'utf8'));
    const deps = Object.keys({ ...pkg.dependencies, ...pkg.devDependencies });
    return `name: ${pkg.name ?? '?'}\nversion: ${pkg.version ?? '?'}\nscripts: ${Object.keys(pkg.scripts ?? {}).join(', ')}\ndependencies (${deps.length}): ${deps.join(', ')}`;
  } catch {
    return '(unreadable)';
  }
}

function readReadme(cwd: string): string {
  for (const name of ['README.md', 'readme.md', 'README.txt', 'README']) {
    const file = path.join(cwd, name);
    if (fs.existsSync(file)) {
      try { return fs.readFileSync(file, 'utf8').slice(0, 5000); } catch {}
    }
  }
  return '(not found)';
}

function readConfigFiles(cwd: string): string {
  const candidates = [
    'tsconfig.json', 'jsconfig.json',
    '.env.example', '.env.sample', '.env.template',
    'docker-compose.yml', 'docker-compose.yaml',
    'angular.json', 'nest-cli.json', 'vite.config.ts', 'vite.config.js',
    'next.config.js', 'next.config.ts',
  ];

  const parts: string[] = [];
  for (const name of candidates) {
    const file = path.join(cwd, name);
    if (!fs.existsSync(file)) continue;
    try {
      const content = fs.readFileSync(file, 'utf8').slice(0, 1000);
      parts.push(`--- ${name} ---\n${content}`);
    } catch {}
    if (parts.length >= 5) break;
  }
  return parts.join('\n\n') || '(none found)';
}

type FileFilter = RegExp | ((name: string) => boolean);

function matchesFilter(name: string, filter: FileFilter): boolean {
  return typeof filter === 'function' ? filter(name) : filter.test(name);
}

function srcRoots(cwd: string): string[] {
  return ['src', 'app', 'lib', 'packages', 'modules', 'server', 'api']
    .map(d => path.join(cwd, d))
    .filter(d => { try { return fs.statSync(d).isDirectory(); } catch { return false; } });
}

function gatherFiles(roots: string[], pattern: FileFilter, maxDepth: number, limit: number): string[] {
  const out: string[] = [];
  for (const root of roots) {
    collectFiles(root, out, pattern, maxDepth);
    if (out.length >= limit) break;
  }
  return out;
}

function appendUnique(files: string[], limit: number, seen: Set<string>, sections: string[], maxChars: number, prefix = ''): void {
  for (const f of files.slice(0, limit)) {
    if (seen.has(f)) continue;
    seen.add(f);
    sections.push(formatFile(f, maxChars, prefix));
  }
}

function readSourceFiles(cwd: string): string {
  const roots = srcRoots(cwd);
  const entryFiles   = gatherFiles(roots, ENTRY_PATTERN,  2, 4);
  const logicFiles   = gatherFiles(roots, isLogicFile,    5, 15);
  const testFiles    = gatherFiles(roots, TEST_PATTERN,   5, 8);
  const generalFiles = gatherFiles(roots, SOURCE_EXT,     5, 20);

  const seen = new Set<string>();
  const sections: string[] = [];

  appendUnique(entryFiles,   4,  seen, sections, 2500);
  appendUnique(logicFiles,   15, seen, sections, 1500);
  appendUnique(testFiles,    8,  seen, sections, 1200, '[TEST] ');

  for (const f of generalFiles) {
    if (seen.has(f) || seen.size >= 30) break;
    seen.add(f);
    sections.push(formatFile(f, 1000));
  }

  return sections.join('\n\n').slice(0, 30000);
}

function formatFile(filePath: string, maxChars: number, prefix = ''): string {
  const rel = path.basename(filePath);
  try {
    const content = fs.readFileSync(filePath, 'utf8').slice(0, maxChars);
    return `--- ${prefix}${rel} ---\n${content}`;
  } catch {
    return `--- ${prefix}${rel} --- (unreadable)`;
  }
}

function visitEntry(full: string, entry: string, out: string[], filter: FileFilter, maxDepth: number, depth: number): void {
  try {
    const stat = fs.statSync(full);
    if (stat.isFile() && matchesFilter(entry, filter) && !out.includes(full)) {
      out.push(full);
    } else if (stat.isDirectory()) {
      collectFiles(full, out, filter, maxDepth, depth + 1);
    }
  } catch {}
}

function collectFiles(dir: string, out: string[], filter: FileFilter, maxDepth: number, depth = 0): void {
  if (depth > maxDepth || out.length >= 20) return;
  let entries: string[];
  try { entries = fs.readdirSync(dir); } catch { return; }

  for (const entry of entries) {
    if (IGNORED.has(entry)) continue;
    visitEntry(path.join(dir, entry), entry, out, filter, maxDepth, depth);
    if (out.length >= 20) break;
  }
}
